// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOJSTQHqhQCdUrdA7KTWINnrCiNsf6qo',
    appId: '1:596649078728:web:28e61b84f6d549a5f49afd',
    messagingSenderId: '596649078728',
    projectId: 'flutter-app-4a-chmc',
    authDomain: 'flutter-app-4a-chmc.firebaseapp.com',
    storageBucket: 'flutter-app-4a-chmc.firebasestorage.app',
    measurementId: 'G-NGYRF2GS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEA5QfPOm6uqxOFZHaQA9I7JbBd9pyP5o',
    appId: '1:596649078728:android:5c483d16de33fc8bf49afd',
    messagingSenderId: '596649078728',
    projectId: 'flutter-app-4a-chmc',
    storageBucket: 'flutter-app-4a-chmc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI49STrtQ9C8fd-SlecUgSqE5dzr7yuzM',
    appId: '1:596649078728:ios:1d818834991a6a7bf49afd',
    messagingSenderId: '596649078728',
    projectId: 'flutter-app-4a-chmc',
    storageBucket: 'flutter-app-4a-chmc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI49STrtQ9C8fd-SlecUgSqE5dzr7yuzM',
    appId: '1:596649078728:ios:1d818834991a6a7bf49afd',
    messagingSenderId: '596649078728',
    projectId: 'flutter-app-4a-chmc',
    storageBucket: 'flutter-app-4a-chmc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOJSTQHqhQCdUrdA7KTWINnrCiNsf6qo',
    appId: '1:596649078728:web:730ea4ba7743d5edf49afd',
    messagingSenderId: '596649078728',
    projectId: 'flutter-app-4a-chmc',
    authDomain: 'flutter-app-4a-chmc.firebaseapp.com',
    storageBucket: 'flutter-app-4a-chmc.firebasestorage.app',
    measurementId: 'G-P54H5RHC7H',
  );

}